export enum TWErrorCodes {
  CALL_EXCEPTION = 'CALL_EXCEPTION',
  CONFIG_ERROR = 'CONFIG_ERROR',

  WALLET_NOT_OWNED = 'WALLET_NOT_OWNED',
  WALLET_NOT_READY = 'WALLET_NOT_READY',

  MODULE_ALREADY_INSTALLED = 'MODULE_ALREADY_INSTALLED',
  MODULE_NOT_INSTALLED = 'MODULE_NOT_INSTALLED',
  MODULE_NOT_SUPPORTED = 'MODULE_NOT_SUPPORTED',


  INVALID_SIGNER_TYPE = 'INVALID_SIGNER_TYPE',
  JWT_INIT_SIGNER_ERROR = 'JWT_INIT_SIGNER_ERROR',
  JWT_SIGNER_INVALID_JWT = 'JWT_SIGNER_INVALID_JWT',
  JWT_SIGNER_INVALID_KEY = 'JWT_SIGNER_INVALID_KEY',
  JWT_SIGNER_LIMIT = 'JWT_SIGNER_LIMIT',
  JWT_SIGNER_INITIALIZED = 'JWT_SIGNER_INITIALIZED',
}
