export enum TrueWalletErrorCodes {
  CALL_EXCEPTION = 'CALL_EXCEPTION',
  CONFIG_ERROR = 'CONFIG_ERROR',

  WALLET_NOT_OWNED = 'WALLET_NOT_OWNED',
  WALLET_NOT_READY = 'WALLET_NOT_READY',

  MODULE_ALREADY_INSTALLED = 'MODULE_ALREADY_INSTALLED',
  MODULE_NOT_INSTALLED = 'MODULE_NOT_INSTALLED',
  MODULE_NOT_SUPPORTED = 'MODULE_NOT_SUPPORTED',
}
